# Generated by Django 5.2 on 2025-06-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='titre',
            field=models.CharField(default='Alerte de sécurité', max_length=255),
        ),
    ]
