# Generated by Django 5.2 on 2025-06-20 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alert_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='detected_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
