# Generated by Django 5.2 on 2025-06-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_alert_detected_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
