# Generated by Django 5.2 on 2025-06-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alert_is_email_sent_alert_is_sms_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
