# Generated by Django 5.2 on 2025-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alert_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='ia_analysis',
            field=models.TextField(blank=True, help_text="Explication intelligente de l'alerte et recommandation IA", null=True),
        ),
    ]
