# Generated by Django 5.2.3 on 2025-07-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_deviceevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('technicien', 'Technicien'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=20),
        ),
    ]
