# Generated by Django 5.2.3 on 2025-06-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='transaction_id',
            field=models.CharField(default=1111, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
