# Generated by Django 5.2.3 on 2025-06-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_abonnement_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='date_fin',
            field=models.DateTimeField(default='2025-06-29 18:11:33'),
            preserve_default=False,
        ),
    ]
