# Generated by Django 5.2.3 on 2025-06-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_abonnement_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
