# Generated by Django 5.2.3 on 2025-06-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_abonnement_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='licence',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
