# Generated by Django 5.2.3 on 2025-07-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_abonnement_licence_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
