# Generated by Django 5.2.3 on 2025-07-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_abonnement_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('entreprise', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('sujet', models.CharField(choices=[('information', 'Demande d’information'), ('devis', 'Demande de devis'), ('support', 'Support technique'), ('licence', 'Problème de licence'), ('partenariat', 'Partenariat'), ('autre', 'Autre')], max_length=50)),
                ('message', models.TextField()),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='LicenseKey',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
